package com.shopping.mall.themall.model;

import java.util.Date;

public class Brand {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_brand.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_brand.addtime
     *
     * @mbggenerated
     */
    private Date addtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_brand.deletestatus
     *
     * @mbggenerated
     */
    private Boolean deletestatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_brand.initial
     *
     * @mbggenerated
     */
    private String initial;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_brand.brand_name
     *
     * @mbggenerated
     */
    private String brandName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_brand.imgpath
     *
     * @mbggenerated
     */
    private String imgpath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_brand.recommend
     *
     * @mbggenerated
     */
    private Boolean recommend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_brand.req
     *
     * @mbggenerated
     */
    private Integer req;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_brand.id
     *
     * @return the value of shopping_brand.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_brand.id
     *
     * @param id the value for shopping_brand.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_brand.addtime
     *
     * @return the value of shopping_brand.addtime
     *
     * @mbggenerated
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_brand.addtime
     *
     * @param addtime the value for shopping_brand.addtime
     *
     * @mbggenerated
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_brand.deletestatus
     *
     * @return the value of shopping_brand.deletestatus
     *
     * @mbggenerated
     */
    public Boolean getDeletestatus() {
        return deletestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_brand.deletestatus
     *
     * @param deletestatus the value for shopping_brand.deletestatus
     *
     * @mbggenerated
     */
    public void setDeletestatus(Boolean deletestatus) {
        this.deletestatus = deletestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_brand.initial
     *
     * @return the value of shopping_brand.initial
     *
     * @mbggenerated
     */
    public String getInitial() {
        return initial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_brand.initial
     *
     * @param initial the value for shopping_brand.initial
     *
     * @mbggenerated
     */
    public void setInitial(String initial) {
        this.initial = initial == null ? null : initial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_brand.brand_name
     *
     * @return the value of shopping_brand.brand_name
     *
     * @mbggenerated
     */
    public String getBrandName() {
        return brandName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_brand.brand_name
     *
     * @param brandName the value for shopping_brand.brand_name
     *
     * @mbggenerated
     */
    public void setBrandName(String brandName) {
        this.brandName = brandName == null ? null : brandName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_brand.imgpath
     *
     * @return the value of shopping_brand.imgpath
     *
     * @mbggenerated
     */
    public String getImgpath() {
        return imgpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_brand.imgpath
     *
     * @param imgpath the value for shopping_brand.imgpath
     *
     * @mbggenerated
     */
    public void setImgpath(String imgpath) {
        this.imgpath = imgpath == null ? null : imgpath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_brand.recommend
     *
     * @return the value of shopping_brand.recommend
     *
     * @mbggenerated
     */
    public Boolean getRecommend() {
        return recommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_brand.recommend
     *
     * @param recommend the value for shopping_brand.recommend
     *
     * @mbggenerated
     */
    public void setRecommend(Boolean recommend) {
        this.recommend = recommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_brand.req
     *
     * @return the value of shopping_brand.req
     *
     * @mbggenerated
     */
    public Integer getReq() {
        return req;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_brand.req
     *
     * @param req the value for shopping_brand.req
     *
     * @mbggenerated
     */
    public void setReq(Integer req) {
        this.req = req;
    }
}