package com.shopping.mall.themall.model;

import java.math.BigDecimal;
import java.util.Date;

public class DetailOrder {
	private Goods goods;
	
    public Goods getGoods() {
		return goods;
	}

	public void setGoods(Goods goods) {
		this.goods = goods;
	}

	private Integer id;

    private Date addtime;

    private Boolean deletestatus;

    private Integer ordernum;

    private Integer goodsid;

    private Integer count;

    private BigDecimal price;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_detailorder.id
     *
     * @return the value of shopping_detailorder.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_detailorder.id
     *
     * @param id the value for shopping_detailorder.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_detailorder.addtime
     *
     * @return the value of shopping_detailorder.addtime
     *
     * @mbggenerated
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_detailorder.addtime
     *
     * @param addtime the value for shopping_detailorder.addtime
     *
     * @mbggenerated
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_detailorder.deletestatus
     *
     * @return the value of shopping_detailorder.deletestatus
     *
     * @mbggenerated
     */
    public Boolean getDeletestatus() {
        return deletestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_detailorder.deletestatus
     *
     * @param deletestatus the value for shopping_detailorder.deletestatus
     *
     * @mbggenerated
     */
    public void setDeletestatus(Boolean deletestatus) {
        this.deletestatus = deletestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_detailorder.ordernum
     *
     * @return the value of shopping_detailorder.ordernum
     *
     * @mbggenerated
     */
    public Integer getOrdernum() {
        return ordernum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_detailorder.ordernum
     *
     * @param ordernum the value for shopping_detailorder.ordernum
     *
     * @mbggenerated
     */
    public void setOrdernum(Integer ordernum) {
        this.ordernum = ordernum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_detailorder.goodsid
     *
     * @return the value of shopping_detailorder.goodsid
     *
     * @mbggenerated
     */
    public Integer getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_detailorder.goodsid
     *
     * @param goodsid the value for shopping_detailorder.goodsid
     *
     * @mbggenerated
     */
    public void setGoodsid(Integer goodsid) {
        this.goodsid = goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_detailorder.count
     *
     * @return the value of shopping_detailorder.count
     *
     * @mbggenerated
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_detailorder.count
     *
     * @param count the value for shopping_detailorder.count
     *
     * @mbggenerated
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_detailorder.price
     *
     * @return the value of shopping_detailorder.price
     *
     * @mbggenerated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_detailorder.price
     *
     * @param price the value for shopping_detailorder.price
     *
     * @mbggenerated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }
}