package com.shopping.mall.themall.model;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

public class Goods {

    private Integer id;
    private Sort sort;
    private Brand brand;
    private List<GoodsAndSpecv> listGoodsAndSpecv;
    

	public List<GoodsAndSpecv> getListGoodsAndSpecv() {
		return listGoodsAndSpecv;
	}

	public void setListGoodsAndSpecv(List<GoodsAndSpecv> listGoodsAndSpecv) {
		this.listGoodsAndSpecv = listGoodsAndSpecv;
	}

	public Sort getSort() {
		return sort;
	}

	public void setSort(Sort sort) {
		this.sort = sort;
	}

	public Brand getBrand() {
		return brand;
	}

	public void setBrand(Brand brand) {
		this.brand = brand;
	}

    private Date addtime;

    private Boolean deletestatus;

    private String goodname;

    private BigDecimal oldprice;

    private BigDecimal newprice;

    private Float weight;

    private Float volume;

    private Integer stock;

    private Integer sale;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_goods.focus
     *
     * @mbggenerated
     */
    private Integer focus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_goods.imgpath
     *
     * @mbggenerated
     */
    private String imgpath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_goods.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_goods.brandid
     *
     * @mbggenerated
     */
    private Integer brandid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_goods.sortid
     *
     * @mbggenerated
     */
    private Integer sortid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_goods.statu
     *
     * @mbggenerated
     */
    private Boolean statu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_goods.recommend
     *
     * @mbggenerated
     */
    private Boolean recommend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_goods.productid
     *
     * @mbggenerated
     */
    private Integer productid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_goods.orderid
     *
     * @mbggenerated
     */
    private Integer orderid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_goods.id
     *
     * @return the value of shopping_goods.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_goods.id
     *
     * @param id the value for shopping_goods.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_goods.addtime
     *
     * @return the value of shopping_goods.addtime
     *
     * @mbggenerated
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_goods.addtime
     *
     * @param addtime the value for shopping_goods.addtime
     *
     * @mbggenerated
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_goods.deletestatus
     *
     * @return the value of shopping_goods.deletestatus
     *
     * @mbggenerated
     */
    public Boolean getDeletestatus() {
        return deletestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_goods.deletestatus
     *
     * @param deletestatus the value for shopping_goods.deletestatus
     *
     * @mbggenerated
     */
    public void setDeletestatus(Boolean deletestatus) {
        this.deletestatus = deletestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_goods.goodname
     *
     * @return the value of shopping_goods.goodname
     *
     * @mbggenerated
     */
    public String getGoodname() {
        return goodname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_goods.goodname
     *
     * @param goodname the value for shopping_goods.goodname
     *
     * @mbggenerated
     */
    public void setGoodname(String goodname) {
        this.goodname = goodname == null ? null : goodname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_goods.oldprice
     *
     * @return the value of shopping_goods.oldprice
     *
     * @mbggenerated
     */
    public BigDecimal getOldprice() {
        return oldprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_goods.oldprice
     *
     * @param oldprice the value for shopping_goods.oldprice
     *
     * @mbggenerated
     */
    public void setOldprice(BigDecimal oldprice) {
        this.oldprice = oldprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_goods.newprice
     *
     * @return the value of shopping_goods.newprice
     *
     * @mbggenerated
     */
    public BigDecimal getNewprice() {
        return newprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_goods.newprice
     *
     * @param newprice the value for shopping_goods.newprice
     *
     * @mbggenerated
     */
    public void setNewprice(BigDecimal newprice) {
        this.newprice = newprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_goods.weight
     *
     * @return the value of shopping_goods.weight
     *
     * @mbggenerated
     */
    public Float getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_goods.weight
     *
     * @param weight the value for shopping_goods.weight
     *
     * @mbggenerated
     */
    public void setWeight(Float weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_goods.volume
     *
     * @return the value of shopping_goods.volume
     *
     * @mbggenerated
     */
    public Float getVolume() {
        return volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_goods.volume
     *
     * @param volume the value for shopping_goods.volume
     *
     * @mbggenerated
     */
    public void setVolume(Float volume) {
        this.volume = volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_goods.stock
     *
     * @return the value of shopping_goods.stock
     *
     * @mbggenerated
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_goods.stock
     *
     * @param stock the value for shopping_goods.stock
     *
     * @mbggenerated
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_goods.sale
     *
     * @return the value of shopping_goods.sale
     *
     * @mbggenerated
     */
    public Integer getSale() {
        return sale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_goods.sale
     *
     * @param sale the value for shopping_goods.sale
     *
     * @mbggenerated
     */
    public void setSale(Integer sale) {
        this.sale = sale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_goods.focus
     *
     * @return the value of shopping_goods.focus
     *
     * @mbggenerated
     */
    public Integer getFocus() {
        return focus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_goods.focus
     *
     * @param focus the value for shopping_goods.focus
     *
     * @mbggenerated
     */
    public void setFocus(Integer focus) {
        this.focus = focus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_goods.imgpath
     *
     * @return the value of shopping_goods.imgpath
     *
     * @mbggenerated
     */
    public String getImgpath() {
        return imgpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_goods.imgpath
     *
     * @param imgpath the value for shopping_goods.imgpath
     *
     * @mbggenerated
     */
    public void setImgpath(String imgpath) {
        this.imgpath = imgpath == null ? null : imgpath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_goods.description
     *
     * @return the value of shopping_goods.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_goods.description
     *
     * @param description the value for shopping_goods.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_goods.brandid
     *
     * @return the value of shopping_goods.brandid
     *
     * @mbggenerated
     */
    public Integer getBrandid() {
        return brandid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_goods.brandid
     *
     * @param brandid the value for shopping_goods.brandid
     *
     * @mbggenerated
     */
    public void setBrandid(Integer brandid) {
        this.brandid = brandid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_goods.sortid
     *
     * @return the value of shopping_goods.sortid
     *
     * @mbggenerated
     */
    public Integer getSortid() {
        return sortid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_goods.sortid
     *
     * @param sortid the value for shopping_goods.sortid
     *
     * @mbggenerated
     */
    public void setSortid(Integer sortid) {
        this.sortid = sortid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_goods.statu
     *
     * @return the value of shopping_goods.statu
     *
     * @mbggenerated
     */
    public Boolean getStatu() {
        return statu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_goods.statu
     *
     * @param statu the value for shopping_goods.statu
     *
     * @mbggenerated
     */
    public void setStatu(Boolean statu) {
        this.statu = statu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_goods.recommend
     *
     * @return the value of shopping_goods.recommend
     *
     * @mbggenerated
     */
    public Boolean getRecommend() {
        return recommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_goods.recommend
     *
     * @param recommend the value for shopping_goods.recommend
     *
     * @mbggenerated
     */
    public void setRecommend(Boolean recommend) {
        this.recommend = recommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_goods.productid
     *
     * @return the value of shopping_goods.productid
     *
     * @mbggenerated
     */
    public Integer getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_goods.productid
     *
     * @param productid the value for shopping_goods.productid
     *
     * @mbggenerated
     */
    public void setProductid(Integer productid) {
        this.productid = productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_goods.orderid
     *
     * @return the value of shopping_goods.orderid
     *
     * @mbggenerated
     */
    public Integer getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_goods.orderid
     *
     * @param orderid the value for shopping_goods.orderid
     *
     * @mbggenerated
     */
    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }
}