package com.shopping.mall.themall.model;

import java.util.List;

public class GoodsAndSpecv {

    private Integer id;

    private Integer productid;

    private Integer specvid;

    private Integer goodsid;

    private Integer specid;
    private Specv specv;
    
    private Spec spec;
    private List<Specv> listSpecv;
    

	public List<Specv> getListSpecv() {
		return listSpecv;
	}

	public void setListSpecv(List<Specv> listSpecv) {
		this.listSpecv = listSpecv;
	}

	public Specv getSpecv() {
		return specv;
	}

	public void setSpecv(Specv specv) {
		this.specv = specv;
	}

	public Spec getSpec() {
		return spec;
	}

	public void setSpec(Spec spec) {
		this.spec = spec;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_goodsandspecv.id
     *
     * @return the value of shopping_goodsandspecv.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_goodsandspecv.id
     *
     * @param id the value for shopping_goodsandspecv.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_goodsandspecv.productid
     *
     * @return the value of shopping_goodsandspecv.productid
     *
     * @mbggenerated
     */
    public Integer getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_goodsandspecv.productid
     *
     * @param productid the value for shopping_goodsandspecv.productid
     *
     * @mbggenerated
     */
    public void setProductid(Integer productid) {
        this.productid = productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_goodsandspecv.specvid
     *
     * @return the value of shopping_goodsandspecv.specvid
     *
     * @mbggenerated
     */
    public Integer getSpecvid() {
        return specvid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_goodsandspecv.specvid
     *
     * @param specvid the value for shopping_goodsandspecv.specvid
     *
     * @mbggenerated
     */
    public void setSpecvid(Integer specvid) {
        this.specvid = specvid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_goodsandspecv.goodsid
     *
     * @return the value of shopping_goodsandspecv.goodsid
     *
     * @mbggenerated
     */
    public Integer getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_goodsandspecv.goodsid
     *
     * @param goodsid the value for shopping_goodsandspecv.goodsid
     *
     * @mbggenerated
     */
    public void setGoodsid(Integer goodsid) {
        this.goodsid = goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_goodsandspecv.specid
     *
     * @return the value of shopping_goodsandspecv.specid
     *
     * @mbggenerated
     */
    public Integer getSpecid() {
        return specid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_goodsandspecv.specid
     *
     * @param specid the value for shopping_goodsandspecv.specid
     *
     * @mbggenerated
     */
    public void setSpecid(Integer specid) {
        this.specid = specid;
    }
}