package com.shopping.mall.themall.model;

import java.util.Date;

public class Img {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_img.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_img.addtime
     *
     * @mbggenerated
     */
    private Date addtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_img.imgpath
     *
     * @mbggenerated
     */
    private String imgpath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_img.goodsid
     *
     * @mbggenerated
     */
    private Integer goodsid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_img.id
     *
     * @return the value of shopping_img.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_img.id
     *
     * @param id the value for shopping_img.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_img.addtime
     *
     * @return the value of shopping_img.addtime
     *
     * @mbggenerated
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_img.addtime
     *
     * @param addtime the value for shopping_img.addtime
     *
     * @mbggenerated
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_img.imgpath
     *
     * @return the value of shopping_img.imgpath
     *
     * @mbggenerated
     */
    public String getImgpath() {
        return imgpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_img.imgpath
     *
     * @param imgpath the value for shopping_img.imgpath
     *
     * @mbggenerated
     */
    public void setImgpath(String imgpath) {
        this.imgpath = imgpath == null ? null : imgpath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_img.goodsid
     *
     * @return the value of shopping_img.goodsid
     *
     * @mbggenerated
     */
    public Integer getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_img.goodsid
     *
     * @param goodsid the value for shopping_img.goodsid
     *
     * @mbggenerated
     */
    public void setGoodsid(Integer goodsid) {
        this.goodsid = goodsid;
    }
}