package com.shopping.mall.themall.model;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

public class Order {
	private User user;
	
	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	private List<DetailOrder> listDetailOrder;
	
    public List<DetailOrder> getListDetailOrder() {
		return listDetailOrder;
	}

	public void setListDetailOrder(List<DetailOrder> listDetailOrder) {
		this.listDetailOrder = listDetailOrder;
	}

	private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_order.addtime
     *
     * @mbggenerated
     */
    private Date addtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_order.deletestatus
     *
     * @mbggenerated
     */
    private Boolean deletestatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_order.ordernum
     *
     * @mbggenerated
     */
    private String ordernum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_order.orderstatus
     *
     * @mbggenerated
     */
    private Integer orderstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_order.ordersum
     *
     * @mbggenerated
     */
    private BigDecimal ordersum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_order.userid
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_order.detailaddress
     *
     * @mbggenerated
     */
    private String detailaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_order.procityarea
     *
     * @mbggenerated
     */
    private String procityarea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_order.postcodecode
     *
     * @mbggenerated
     */
    private String postcodecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_order.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_order.consigneename
     *
     * @mbggenerated
     */
    private String consigneename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_order.id
     *
     * @return the value of shopping_order.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_order.id
     *
     * @param id the value for shopping_order.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_order.addtime
     *
     * @return the value of shopping_order.addtime
     *
     * @mbggenerated
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_order.addtime
     *
     * @param addtime the value for shopping_order.addtime
     *
     * @mbggenerated
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_order.deletestatus
     *
     * @return the value of shopping_order.deletestatus
     *
     * @mbggenerated
     */
    public Boolean getDeletestatus() {
        return deletestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_order.deletestatus
     *
     * @param deletestatus the value for shopping_order.deletestatus
     *
     * @mbggenerated
     */
    public void setDeletestatus(Boolean deletestatus) {
        this.deletestatus = deletestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_order.ordernum
     *
     * @return the value of shopping_order.ordernum
     *
     * @mbggenerated
     */
    public String getOrdernum() {
        return ordernum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_order.ordernum
     *
     * @param ordernum the value for shopping_order.ordernum
     *
     * @mbggenerated
     */
    public void setOrdernum(String ordernum) {
        this.ordernum = ordernum == null ? null : ordernum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_order.orderstatus
     *
     * @return the value of shopping_order.orderstatus
     *
     * @mbggenerated
     */
    public Integer getOrderstatus() {
        return orderstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_order.orderstatus
     *
     * @param orderstatus the value for shopping_order.orderstatus
     *
     * @mbggenerated
     */
    public void setOrderstatus(Integer orderstatus) {
        this.orderstatus = orderstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_order.ordersum
     *
     * @return the value of shopping_order.ordersum
     *
     * @mbggenerated
     */
    public BigDecimal getOrdersum() {
        return ordersum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_order.ordersum
     *
     * @param ordersum the value for shopping_order.ordersum
     *
     * @mbggenerated
     */
    public void setOrdersum(BigDecimal ordersum) {
        this.ordersum = ordersum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_order.userid
     *
     * @return the value of shopping_order.userid
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_order.userid
     *
     * @param userid the value for shopping_order.userid
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_order.detailaddress
     *
     * @return the value of shopping_order.detailaddress
     *
     * @mbggenerated
     */
    public String getDetailaddress() {
        return detailaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_order.detailaddress
     *
     * @param detailaddress the value for shopping_order.detailaddress
     *
     * @mbggenerated
     */
    public void setDetailaddress(String detailaddress) {
        this.detailaddress = detailaddress == null ? null : detailaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_order.procityarea
     *
     * @return the value of shopping_order.procityarea
     *
     * @mbggenerated
     */
    public String getProcityarea() {
        return procityarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_order.procityarea
     *
     * @param procityarea the value for shopping_order.procityarea
     *
     * @mbggenerated
     */
    public void setProcityarea(String procityarea) {
        this.procityarea = procityarea == null ? null : procityarea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_order.postcodecode
     *
     * @return the value of shopping_order.postcodecode
     *
     * @mbggenerated
     */
    public String getPostcodecode() {
        return postcodecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_order.postcodecode
     *
     * @param postcodecode the value for shopping_order.postcodecode
     *
     * @mbggenerated
     */
    public void setPostcodecode(String postcodecode) {
        this.postcodecode = postcodecode == null ? null : postcodecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_order.phone
     *
     * @return the value of shopping_order.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_order.phone
     *
     * @param phone the value for shopping_order.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_order.consigneename
     *
     * @return the value of shopping_order.consigneename
     *
     * @mbggenerated
     */
    public String getConsigneename() {
        return consigneename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_order.consigneename
     *
     * @param consigneename the value for shopping_order.consigneename
     *
     * @mbggenerated
     */
    public void setConsigneename(String consigneename) {
        this.consigneename = consigneename == null ? null : consigneename.trim();
    }
}