package com.shopping.mall.themall.model;

import java.util.Date;
import java.util.List;

public class Sort {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_sort.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_sort.addtime
     *
     * @mbggenerated
     */
    private Date addtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_sort.deletestatus
     *
     * @mbggenerated
     */
    private Boolean deletestatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_sort.sort_name
     *
     * @mbggenerated
     */
    private String sortName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_sort.sort
     *
     * @mbggenerated
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_sort.parentid
     *
     * @mbggenerated
     */
    private Integer parentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_sort.display
     *
     * @mbggenerated
     */
    private Boolean display;
    private List<Sort> listSort2;
    private List<Sort> listSort3;

    public List<Sort> getListSort2() {
		return listSort2;
	}

	public void setListSort2(List<Sort> listSort2) {
		this.listSort2 = listSort2;
	}

	public List<Sort> getListSort3() {
		return listSort3;
	}

	public void setListSort3(List<Sort> listSort3) {
		this.listSort3 = listSort3;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_sort.id
     *
     * @return the value of shopping_sort.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_sort.id
     *
     * @param id the value for shopping_sort.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_sort.addtime
     *
     * @return the value of shopping_sort.addtime
     *
     * @mbggenerated
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_sort.addtime
     *
     * @param addtime the value for shopping_sort.addtime
     *
     * @mbggenerated
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_sort.deletestatus
     *
     * @return the value of shopping_sort.deletestatus
     *
     * @mbggenerated
     */
    public Boolean getDeletestatus() {
        return deletestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_sort.deletestatus
     *
     * @param deletestatus the value for shopping_sort.deletestatus
     *
     * @mbggenerated
     */
    public void setDeletestatus(Boolean deletestatus) {
        this.deletestatus = deletestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_sort.sort_name
     *
     * @return the value of shopping_sort.sort_name
     *
     * @mbggenerated
     */
    public String getSortName() {
        return sortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_sort.sort_name
     *
     * @param sortName the value for shopping_sort.sort_name
     *
     * @mbggenerated
     */
    public void setSortName(String sortName) {
        this.sortName = sortName == null ? null : sortName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_sort.sort
     *
     * @return the value of shopping_sort.sort
     *
     * @mbggenerated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_sort.sort
     *
     * @param sort the value for shopping_sort.sort
     *
     * @mbggenerated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_sort.parentid
     *
     * @return the value of shopping_sort.parentid
     *
     * @mbggenerated
     */
    public Integer getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_sort.parentid
     *
     * @param parentid the value for shopping_sort.parentid
     *
     * @mbggenerated
     */
    public void setParentid(Integer parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_sort.display
     *
     * @return the value of shopping_sort.display
     *
     * @mbggenerated
     */
    public Boolean getDisplay() {
        return display;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_sort.display
     *
     * @param display the value for shopping_sort.display
     *
     * @mbggenerated
     */
    public void setDisplay(Boolean display) {
        this.display = display;
    }
}