package com.shopping.mall.themall.model;

import java.util.Date;
import java.util.List;

public class Spec {
    private Integer id;

    private Date addtime;

    private Boolean deletestatus;

    private String specname;

    private Integer seq;
    
    private List<Specv> listSpecv;
    

    public List<Specv> getListSpecv() {
		return listSpecv;
	}

	public void setListSpecv(List<Specv> listSpecv) {
		this.listSpecv = listSpecv;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_spec.id
     *
     * @return the value of shopping_spec.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_spec.id
     *
     * @param id the value for shopping_spec.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_spec.addtime
     *
     * @return the value of shopping_spec.addtime
     *
     * @mbggenerated
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_spec.addtime
     *
     * @param addtime the value for shopping_spec.addtime
     *
     * @mbggenerated
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_spec.deletestatus
     *
     * @return the value of shopping_spec.deletestatus
     *
     * @mbggenerated
     */
    public Boolean getDeletestatus() {
        return deletestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_spec.deletestatus
     *
     * @param deletestatus the value for shopping_spec.deletestatus
     *
     * @mbggenerated
     */
    public void setDeletestatus(Boolean deletestatus) {
        this.deletestatus = deletestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_spec.specname
     *
     * @return the value of shopping_spec.specname
     *
     * @mbggenerated
     */
    public String getSpecname() {
        return specname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_spec.specname
     *
     * @param specname the value for shopping_spec.specname
     *
     * @mbggenerated
     */
    public void setSpecname(String specname) {
        this.specname = specname == null ? null : specname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_spec.seq
     *
     * @return the value of shopping_spec.seq
     *
     * @mbggenerated
     */
    public Integer getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_spec.seq
     *
     * @param seq the value for shopping_spec.seq
     *
     * @mbggenerated
     */
    public void setSeq(Integer seq) {
        this.seq = seq;
    }
}