package com.shopping.mall.themall.model;

import java.util.Date;

public class Specv {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_specv.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_specv.addtime
     *
     * @mbggenerated
     */
    private Date addtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_specv.specvname
     *
     * @mbggenerated
     */
    private String specvname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_specv.seq
     *
     * @mbggenerated
     */
    private Integer seq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_specv.specid
     *
     * @mbggenerated
     */
    private Integer specid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_specv.id
     *
     * @return the value of shopping_specv.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_specv.id
     *
     * @param id the value for shopping_specv.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_specv.addtime
     *
     * @return the value of shopping_specv.addtime
     *
     * @mbggenerated
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_specv.addtime
     *
     * @param addtime the value for shopping_specv.addtime
     *
     * @mbggenerated
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_specv.specvname
     *
     * @return the value of shopping_specv.specvname
     *
     * @mbggenerated
     */
    public String getSpecvname() {
        return specvname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_specv.specvname
     *
     * @param specvname the value for shopping_specv.specvname
     *
     * @mbggenerated
     */
    public void setSpecvname(String specvname) {
        this.specvname = specvname == null ? null : specvname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_specv.seq
     *
     * @return the value of shopping_specv.seq
     *
     * @mbggenerated
     */
    public Integer getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_specv.seq
     *
     * @param seq the value for shopping_specv.seq
     *
     * @mbggenerated
     */
    public void setSeq(Integer seq) {
        this.seq = seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_specv.specid
     *
     * @return the value of shopping_specv.specid
     *
     * @mbggenerated
     */
    public Integer getSpecid() {
        return specid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_specv.specid
     *
     * @param specid the value for shopping_specv.specid
     *
     * @mbggenerated
     */
    public void setSpecid(Integer specid) {
        this.specid = specid;
    }
}